apiVersion: apps/v1
kind: Deployment
metadata:
  name: xpanel-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xpanel
  template:
    metadata:
      labels:
        app: xpanel
    spec:
      containers:
      - name: xpanel
        image: your_docker_image
        ports:
        - containerPort: 8000
